grafana:
    adminUser: "adminsky"
    persistence:
        enabled: true
        size: 1Gi
    ingress:
        enabled: false
    grafana.ini:
        server:
            root_url: "https://grafana.jonathanlore.fr"
            domain: "grafana.jonathanlore.fr"

prometheus:
    prometheusSpec:
        # Découverte cross-namespace (surveille the-tip-top-api)
        podMonitorNamespaceSelector: { }
        serviceMonitorNamespaceSelector: { }
        podMonitorSelector: { }
        serviceMonitorSelector: { }

alertmanager:
    enabled: true

nodeExporter:
    enabled: true # métriques infra nœud

kubeStateMetrics:
    enabled: true  # métriques Kubernetes (pods, deployments...)

