apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
        - name: jenkins
          image: joanisky/jenkins-with-docker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: agent
          env:
          - name: JENKINS_OPTS
            value: "--httpPort=8080"
          - name: JAVA_OPTS
            value: >-
              -Xmx2048m
              -Xms1024m
              -XX:+UseG1GC
              -XX:MaxGCPauseMillis=100
              -XX:+DisableExplicitGC
              -Dhudson.slaves.NodeProvisioner.initialDelay=0
          resources:
            requests:
              cpu: "300m"
              memory: "1.5Gi"
            limits:
              cpu: "1000m"
              memory: "3Gi"
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-socket
              mountPath: /var/run/docker.sock
          startupProbe:
            httpGet:
              path: /login
              port: 8080
            failureThreshold: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: jenkins