apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc-db.yaml
  - pvc-matomo.yaml
  - deployment-db.yaml
  - service-db.yaml
  - deployment-matomo.yaml
  - service-matomo.yaml
  - ingress.yaml
