apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-data
  namespace: matomo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
